import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Coffee Shop",
  description: "Generated by create next app",
  icons: {
    icon: "/logo (1).png?v=2", // query string برای جلوگیری از کش
  },
};

export default function RootLayout({ children }) {
  const bgColor = "#1A1011"; // رنگ پس‌زمینه ثابت
  const textColor = "#ededed"; // رنگ متن ثابت

  return (
    <html
      lang="fa"
      style={{
        backgroundColor: bgColor,
        color: textColor,
      }}
      suppressHydrationWarning
    >
      <head>
        {/* جلوگیری از چشمک سفید در موبایل */}
        <meta name="theme-color" content={bgColor} />
        <style>{`
          html, body {
            background-color: ${bgColor} !important;
            color: ${textColor} !important;
            margin: 0;
            padding: 0;
            min-height: 100%;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundColor: bgColor,
          color: textColor,
        }}
      >
        {children}
      </body>
    </html>
  );
}
